### PR TITLE
Bump version to v0.5.0

### PR DESCRIPTION
**Pull request by CaptainVincent**
* Bump version to v0.5.0
* Regenerate generate.rs from [#38 ](https://github.com/WebAssembly/wasi-nn/pull/38)
* Support load_by_name

### CODE REVIEW

**Comment by abrown** [comment]
This looks good, but I would like a chance to clean up a couple things in the witx upstream before we do this bump. I'll do that early next week and then we can rebase this?

**Comment by CaptainVincent** [comment]
👌 Sure. I'll rebase my PR after the new witx release.

**Comment by abrown** [comment]
Ok, I did a bunch of clean up on the specification. Feel free to use that latest WITX to regenerate these bindings.

**Comment by CaptainVincent** [comment]
I'm done with the updates. Could you please help review to see if there are any modifications needed?
Thank you.

**Review by abrown — APPROVED** [review]
LGTM!

**Comment by CaptainVincent** [comment]
WasmEdge has taken the lead in supporting this feature and incorporated it into our [examples](https://github.com/second-state/WasmEdge-WASINN-examples/tree/master/pytorch-mobilenet-image). 
And we almost completed its integration into our ggml (llm) backend implementation, and it will be released alongside the documentation, coming soon 🎉.

**Pull request merged**
