### PR TITLE
image2tensor supports planar format output.

### PR DESCRIPTION
**Pull request by jianjunz**
This change mainly adds support for outputting tensor bytes in planar memory layout, or [CHW](https://oneapi-src.github.io/oneDNN/dev_guide_understanding_memory_formats.html#nchw) format. Besides this, it also adds support for png input with alpha channel (output still doesn't have alpha channel, so it's stripped out).

### CODE REVIEW

**Review by abrown — APPROVED** [review]

**Comment by abrown** [comment]
cc: @geekbeast

**Comment by abrown** [comment]
I guess one of us should try to fix CI; @jianjunz, we can talk about this more next week. The current job is a bit of a scripted monolith that we might need to refactor. But then again, it's not too useful to spend a lot of time on this since the bindings portion of this could be replaced by `wit-bindgen`-generated bindings for wasi-nn.

**Comment by jianjunz** [comment]
Thanks for your review. Please help merge if it looks good.

The CI failure is caused by openvino checksum mismatch. It may need an update.

**Comment by geekbeast** [comment]
A bit late, but this looks good to me.

**Pull request merged**
